marker_1_id: 1
marker_1_x: 2.0
marker_1_y: 3.0
marker_1_z: 0.0

marker_2_id: 2
marker_2_x: 2.0
marker_2_y: 3.0
marker_2_z: 0.0

marker_3_id: 3
marker_3_x: 2.0
marker_3_y: 3.0
marker_3_z: 0.0

marker_4_id: 4
marker_4_x: 1.5
marker_4_y: 8.5
marker_4_z: 0.0

marker_5_id: 5
marker_5_x: 2.0
marker_5_y: 3.0
marker_5_z: 0.0

marker_6_id: 6
marker_6_x: 2.0
marker_6_y: 3.0
marker_6_z: 0.0

marker_7_id: 7
marker_7_x: 2.0
marker_7_y: 3.0
marker_7_z: 0.0

marker_8_id: 8
marker_8_x: 2.0
marker_8_y: 3.0
marker_8_z: 0.0

marker_9_id: 9
marker_9_x: 2.0
marker_9_y: 3.0
marker_9_z: 0.0

marker_10_id: 10
marker_10_x: 2.0
marker_10_y: 3.0
marker_10_z: 0.0