ptz_camera:
   joint_state_controller:
     type: joint_state_controller/JointStateController
     publish_rate: 50
   tilt_position_controller:
     type: position_controllers/JointPositionController
     joint: tilt
     pid: {p: 100.0, i: 0.01, d: 10.0 }
   pan_position_controller:
     type: position_controllers/JointPositionController
     joint: pan
     pid: {p: 100.0, i: 0.01, d: 10.0 }
